[package]
name = "bpdump"
description = "Bitcoin protocol Swiss army knife - like `tcpdump`, but for LNP/BP stack"
version = "0.1.0"
license = "MIT"
authors = ["Dr Maxim Orlovsky <orlovsky@datagnition.com>"]
keywords = [ "bitcoin", "lightning", "blockchain" ]
readme = "README.md"
edition = "2018"

[dependencies]
yaml = "0.3.0"
bitcoin = "~0.19.0"
bech32 = "~0.6.0"
bitcoin-bech32 = "~0.9.0"
bitcoin_hashes = "~0.3.0"

[patch.crates-io]
bitcoin = { git = "https://github.com/pandoracore/rust-bitcoin.git", branch = "generic-reader" }

[dependencies.secp256k1]
version = "~0.12.0" # We require this version because of compatibility issues with bitcoin 0.18.0
features = [ "rand" ]

[dependencies.clap]
version = "~2.33"
default-features = true
features = [ "yaml" ]
