[package]
name = "bp_node"
description = "Bitcoin protocol node"
version = "0.1.0"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>"]
keywords = ["bitcoin", "node"]
license = "MIT"
edition = "2018"
readme = "README.md"

[dependencies]
amplify = "~1.2.0"
dotenv = "~0.15"
clap = "=3.0.0-beta.2"
chrono = "~0.4"
derive_wrapper = "~0.1"
async-trait = "~0.1"
log = { version = "~0.4", features = ["max_level_trace", "release_max_level_debug"] }
env_logger = "~0.7"
diesel = { version = "~1.4", features = ["postgres", "uuid", "numeric", "chrono"] }
tokio = { version = "~0.2", features = ["full"] }
futures = "~0.3"
zmq = "~0.9"
tiny_http = "~0.6"
prometheus = "~0.8"

[dependencies.lnpbp]
git = "https://github.com/lnp-bp/rust-lnpbp"
branch = "master"
features = ["tor", "tokio", "serde"]

[patch.crates-io]
# We need this b/c of breaking change in tagged hash type generation
bitcoin_hashes = { git = "https://github.com/LNP-BP/bitcoin_hashes", tag = "lnpbp-v0.1.0-rc1" }
bitcoin = { git = "https://github.com/LNP-BP/rust-bitcoin", tag = "lnpbp-v0.1.0-rc1" }
# We need custom branches here just to depend on the same bitcoin master and do
# not have secp256k1 version conflict
miniscript = { git = "https://github.com/LNP-BP/rust-miniscript", tag = "lnpbp-v0.1.0-rc1" }
# Remove this once https://github.com/jean-airoldie/zeromq-src-rs/pull/15 got merged
zeromq-src = { git = "https://github.com/LNP-BP/zeromq-src-rs", branch = "fix/cmake" }
